# Generated by Django 4.2.5 on 2023-09-14 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Наименование компании')),
                ('description', models.TextField(verbose_name='Описание компании')),
                ('image', models.ImageField(upload_to='companies/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Компания',
                'verbose_name_plural': 'Компании',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Наименование продукта')),
                ('description', models.TextField(default='Здесь скоро будет описание', verbose_name='Описание продукта')),
                ('price', models.FloatField(verbose_name='Цена продукта')),
                ('color', models.CharField(default='Серебрянный', max_length=150, verbose_name='Цвет продукта')),
                ('material', models.CharField(default='Серебро', max_length=150, verbose_name='Материал продукта')),
                ('size', models.IntegerField(default=40, verbose_name='Размер продукта')),
                ('quantity', models.IntegerField(default=0, verbose_name='Количество на складе')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания продукта')),
                ('slug', models.SlugField(null=True, unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='store.category', verbose_name='Категория продукта')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.company', verbose_name='Компания продукта')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/', verbose_name='Изображение')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='store.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Фотография',
                'verbose_name_plural': 'Фотографии',
            },
        ),
    ]
